spring:
  application:
    name: librarymedia
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/librarymedia?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${DB_USERNAME:librarymedia}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
  mvc:
    problemdetails:
      enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
